services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - 8000:80
    depends_on:
      - postgres
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: laravel-webserver
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - app
    networks:
      - laravel

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: cryptomonnaie
      POSTGRES_PASSWORD: cryptomonnaie
      POSTGRES_DB: cryptomonnaie
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - laravel
    external_links:
      - postgres-db:postgres

volumes:
  postgres_data:

networks:
  laravel:
